"""
Breakthrough Trading Engine
============================

This is the ULTIMATE integration of all intelligence modules.

It replaces the basic signal generation with a sophisticated
multi-factor confluence system that thinks like an institutional trader.

Key improvements over basic system:
1. Multi-timeframe confluence (HTF sets bias, LTF provides entry)
2. Smart Money Concepts (order blocks, FVGs, liquidity)
3. Adaptive regime detection (trend vs range vs volatile)
4. Kelly-optimal position sizing
5. Dynamic stop loss and take profit based on market structure

This is what separates a toy system from a professional one.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from datetime import datetime
import math

from .confluence_engine import ConfluenceEngine, ConfluenceSignal, ConfluenceConfig, TradeDirection, SignalStrength
from .multi_timeframe import Timeframe
from .position_sizer import TradeStats


@dataclass
class BreakthroughConfig:
    """Configuration for the breakthrough engine."""
    # Confluence settings
    min_confluence_score: float = 0.5  # Lower threshold for more trades
    min_risk_reward: float = 1.5
    
    # Position sizing
    max_risk_per_trade: float = 0.02
    max_position_size: float = 0.10
    kelly_fraction: float = 0.25
    
    # Trade management
    use_trailing_stop: bool = True
    trailing_stop_atr_mult: float = 2.0
    partial_profit_at_tp1: float = 0.33  # Take 33% at TP1
    partial_profit_at_tp2: float = 0.33  # Take 33% at TP2
    
    # Filters
    max_spread_pips: float = 3.0
    min_atr_pips: float = 5.0
    max_daily_trades: int = 10
    
    # Time filters
    avoid_news_minutes: int = 30
    trading_hours_start: int = 8  # UTC
    trading_hours_end: int = 20   # UTC


@dataclass
class BreakthroughTrade:
    """A trade generated by the breakthrough engine."""
    signal: ConfluenceSignal
    entry_time: datetime
    entry_price: float
    direction: int  # 1 = long, -1 = short
    stop_loss: float
    take_profit_1: float
    take_profit_2: float
    take_profit_3: float
    position_size: float
    risk_amount: float
    status: str  # "open", "closed", "partial"
    exit_time: Optional[datetime] = None
    exit_price: Optional[float] = None
    pnl: float = 0.0
    pnl_pct: float = 0.0
    exit_reason: str = ""
    partial_exits: List[dict] = field(default_factory=list)


@dataclass
class BreakthroughResult:
    """Result of running the breakthrough engine."""
    trades: List[BreakthroughTrade]
    total_return_pct: float
    sharpe_ratio: float
    max_drawdown_pct: float
    win_rate: float
    profit_factor: float
    avg_rr_achieved: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    avg_trade_duration: float
    equity_curve: List[float]
    reason_codes: List[str]


class BreakthroughEngine:
    """
    The breakthrough trading engine.
    
    This is the culmination of all the intelligence modules working together.
    It generates high-quality trading signals with full confluence analysis.
    """
    
    def __init__(self, config: BreakthroughConfig = None):
        self.config = config or BreakthroughConfig()
        
        # Initialize confluence engine with our config
        confluence_config = ConfluenceConfig(
            min_confluence_score=self.config.min_confluence_score,
            min_risk_reward=self.config.min_risk_reward,
        )
        self.confluence_engine = ConfluenceEngine(confluence_config)
        
        # Trade tracking
        self._trades: List[BreakthroughTrade] = []
        self._equity_curve: List[float] = []
        self._daily_trade_count: Dict[str, int] = {}
    
    def run_backtest(
        self,
        bars: List[dict],
        initial_capital: float = 10000.0,
        spread_pips: float = 1.0,
    ) -> BreakthroughResult:
        """
        Run a full backtest with the breakthrough engine.
        
        Args:
            bars: List of OHLCV bars
            initial_capital: Starting capital
            spread_pips: Spread in pips
            
        Returns:
            BreakthroughResult with full performance metrics
        """
        if len(bars) < 250:
            return self._empty_result("INSUFFICIENT_DATA")
        
        capital = initial_capital
        self._equity_curve = [capital]
        self._trades = []
        self._daily_trade_count = {}
        
        # Track trade statistics for Kelly sizing
        trade_stats = None
        
        # Current open trade
        open_trade: Optional[BreakthroughTrade] = None
        
        # Process each bar
        lookback = 200  # Need 200 bars for analysis
        
        for i in range(lookback, len(bars)):
            current_bar = bars[i]
            history = bars[max(0, i - lookback):i + 1]
            
            current_price = current_bar['close']
            current_high = current_bar['high']
            current_low = current_bar['low']
            
            # Check if we have an open trade
            if open_trade:
                # Check for exit conditions
                exit_price, exit_reason = self._check_exit(
                    open_trade, current_high, current_low, current_price
                )
                
                if exit_price:
                    # Close the trade
                    open_trade.exit_time = self._get_timestamp(current_bar)
                    open_trade.exit_price = exit_price
                    open_trade.exit_reason = exit_reason
                    
                    # Calculate P&L
                    if open_trade.direction == 1:  # Long
                        open_trade.pnl = (exit_price - open_trade.entry_price) * open_trade.position_size
                    else:  # Short
                        open_trade.pnl = (open_trade.entry_price - exit_price) * open_trade.position_size
                    
                    # Subtract spread cost
                    spread_cost = spread_pips * 0.0001 * open_trade.position_size
                    open_trade.pnl -= spread_cost
                    
                    open_trade.pnl_pct = open_trade.pnl / capital
                    open_trade.status = "closed"
                    
                    # Update capital
                    capital += open_trade.pnl
                    
                    # Add to trade history for Kelly
                    self.confluence_engine.position_sizer.add_trade_result(open_trade.pnl_pct)
                    
                    self._trades.append(open_trade)
                    open_trade = None
            
            # Record equity
            self._equity_curve.append(capital)
            
            # If no open trade, look for new signal
            if open_trade is None:
                # Check daily trade limit
                date_str = str(self._get_timestamp(current_bar).date())
                daily_trades = self._daily_trade_count.get(date_str, 0)
                
                if daily_trades >= self.config.max_daily_trades:
                    continue
                
                # Get trade statistics for position sizing
                trade_stats = self.confluence_engine.position_sizer.get_trade_stats()
                
                # Analyze for signal
                signal = self.confluence_engine.analyze(
                    bars=history,
                    capital=capital,
                    trade_stats=trade_stats if trade_stats.total_trades >= 10 else None,
                )
                
                # Check if we have a valid signal
                if signal.direction != TradeDirection.NO_TRADE and signal.strength.value >= SignalStrength.MODERATE.value:
                    # Create trade
                    direction = 1 if signal.direction == TradeDirection.LONG else -1
                    
                    # Adjust entry for spread
                    entry_price = signal.entry_price
                    if direction == 1:
                        entry_price += spread_pips * 0.0001  # Add spread for long
                    
                    open_trade = BreakthroughTrade(
                        signal=signal,
                        entry_time=self._get_timestamp(current_bar),
                        entry_price=entry_price,
                        direction=direction,
                        stop_loss=signal.stop_loss,
                        take_profit_1=signal.take_profit_1,
                        take_profit_2=signal.take_profit_2,
                        take_profit_3=signal.take_profit_3,
                        position_size=signal.position_size.units,
                        risk_amount=signal.position_size.risk_amount,
                        status="open"
                    )
                    
                    # Update daily trade count
                    self._daily_trade_count[date_str] = daily_trades + 1
        
        # Close any remaining open trade at last price
        if open_trade:
            last_price = bars[-1]['close']
            open_trade.exit_time = self._get_timestamp(bars[-1])
            open_trade.exit_price = last_price
            open_trade.exit_reason = "END_OF_DATA"
            
            if open_trade.direction == 1:
                open_trade.pnl = (last_price - open_trade.entry_price) * open_trade.position_size
            else:
                open_trade.pnl = (open_trade.entry_price - last_price) * open_trade.position_size
            
            open_trade.pnl_pct = open_trade.pnl / capital
            open_trade.status = "closed"
            capital += open_trade.pnl
            self._trades.append(open_trade)
        
        # Calculate performance metrics
        return self._calculate_metrics(initial_capital, capital)
    
    def _check_exit(
        self,
        trade: BreakthroughTrade,
        high: float,
        low: float,
        close: float
    ) -> Tuple[Optional[float], str]:
        """Check if trade should be exited."""
        
        if trade.direction == 1:  # Long
            # Check stop loss
            if low <= trade.stop_loss:
                return trade.stop_loss, "STOP_LOSS"
            
            # Check take profits
            if high >= trade.take_profit_3:
                return trade.take_profit_3, "TAKE_PROFIT_3"
            if high >= trade.take_profit_2:
                return trade.take_profit_2, "TAKE_PROFIT_2"
            if high >= trade.take_profit_1:
                return trade.take_profit_1, "TAKE_PROFIT_1"
        
        else:  # Short
            # Check stop loss
            if high >= trade.stop_loss:
                return trade.stop_loss, "STOP_LOSS"
            
            # Check take profits
            if low <= trade.take_profit_3:
                return trade.take_profit_3, "TAKE_PROFIT_3"
            if low <= trade.take_profit_2:
                return trade.take_profit_2, "TAKE_PROFIT_2"
            if low <= trade.take_profit_1:
                return trade.take_profit_1, "TAKE_PROFIT_1"
        
        return None, ""
    
    def _calculate_metrics(self, initial_capital: float, final_capital: float) -> BreakthroughResult:
        """Calculate performance metrics from trades."""
        
        if not self._trades:
            return self._empty_result("NO_TRADES")
        
        # Basic metrics
        total_return_pct = ((final_capital - initial_capital) / initial_capital) * 100
        
        # Win/Loss stats
        winning_trades = [t for t in self._trades if t.pnl > 0]
        losing_trades = [t for t in self._trades if t.pnl <= 0]
        
        win_rate = len(winning_trades) / len(self._trades) if self._trades else 0
        
        # Profit factor
        gross_profit = sum(t.pnl for t in winning_trades)
        gross_loss = abs(sum(t.pnl for t in losing_trades))
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else 0
        
        # Sharpe ratio (annualized)
        returns = [t.pnl_pct for t in self._trades]
        if len(returns) > 1:
            avg_return = sum(returns) / len(returns)
            std_return = math.sqrt(sum((r - avg_return) ** 2 for r in returns) / len(returns))
            sharpe_ratio = (avg_return / std_return) * math.sqrt(252) if std_return > 0 else 0
        else:
            sharpe_ratio = 0
        
        # Max drawdown
        max_drawdown_pct = self._calculate_max_drawdown()
        
        # Average R:R achieved
        rr_achieved = []
        for trade in self._trades:
            if trade.risk_amount > 0:
                rr = trade.pnl / trade.risk_amount
                rr_achieved.append(rr)
        avg_rr = sum(rr_achieved) / len(rr_achieved) if rr_achieved else 0
        
        # Average trade duration (in bars)
        durations = []
        for trade in self._trades:
            if trade.entry_time and trade.exit_time:
                try:
                    # Handle timezone-aware vs naive datetime
                    entry = trade.entry_time
                    exit_t = trade.exit_time
                    if hasattr(entry, 'tzinfo') and entry.tzinfo is not None:
                        entry = entry.replace(tzinfo=None)
                    if hasattr(exit_t, 'tzinfo') and exit_t.tzinfo is not None:
                        exit_t = exit_t.replace(tzinfo=None)
                    duration = (exit_t - entry).total_seconds() / 3600  # hours
                    durations.append(duration)
                except:
                    pass
        avg_duration = sum(durations) / len(durations) if durations else 0
        
        # Collect reason codes
        reason_codes = []
        for trade in self._trades:
            reason_codes.extend(trade.signal.reason_codes[:5])  # Top 5 per trade
        
        return BreakthroughResult(
            trades=self._trades,
            total_return_pct=total_return_pct,
            sharpe_ratio=sharpe_ratio,
            max_drawdown_pct=max_drawdown_pct,
            win_rate=win_rate,
            profit_factor=profit_factor,
            avg_rr_achieved=avg_rr,
            total_trades=len(self._trades),
            winning_trades=len(winning_trades),
            losing_trades=len(losing_trades),
            avg_trade_duration=avg_duration,
            equity_curve=self._equity_curve,
            reason_codes=list(set(reason_codes))[:20]
        )
    
    def _calculate_max_drawdown(self) -> float:
        """Calculate maximum drawdown from equity curve."""
        if not self._equity_curve:
            return 0.0
        
        peak = self._equity_curve[0]
        max_dd = 0.0
        
        for equity in self._equity_curve:
            if equity > peak:
                peak = equity
            dd = (peak - equity) / peak * 100
            if dd > max_dd:
                max_dd = dd
        
        return max_dd
    
    def _get_timestamp(self, bar: dict) -> datetime:
        """Extract timestamp from bar."""
        ts = bar.get('timestamp', '')
        if isinstance(ts, datetime):
            return ts
        if isinstance(ts, str):
            try:
                return datetime.fromisoformat(ts.replace('+00:00', '').replace('Z', ''))
            except:
                pass
        return datetime.now()
    
    def _empty_result(self, reason: str) -> BreakthroughResult:
        """Return empty result."""
        return BreakthroughResult(
            trades=[],
            total_return_pct=0.0,
            sharpe_ratio=0.0,
            max_drawdown_pct=0.0,
            win_rate=0.0,
            profit_factor=0.0,
            avg_rr_achieved=0.0,
            total_trades=0,
            winning_trades=0,
            losing_trades=0,
            avg_trade_duration=0.0,
            equity_curve=[],
            reason_codes=[reason]
        )


def run_breakthrough_backtest(
    bars: List[dict],
    initial_capital: float = 10000.0,
    min_confluence: float = 0.5,
    min_rr: float = 1.5,
) -> BreakthroughResult:
    """
    Convenience function to run a breakthrough backtest.
    
    Args:
        bars: List of OHLCV bars
        initial_capital: Starting capital
        min_confluence: Minimum confluence score for trades
        min_rr: Minimum risk/reward ratio
        
    Returns:
        BreakthroughResult with full performance metrics
    """
    config = BreakthroughConfig(
        min_confluence_score=min_confluence,
        min_risk_reward=min_rr,
    )
    
    engine = BreakthroughEngine(config)
    return engine.run_backtest(bars, initial_capital)
